config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  root "users#index"
  resources :users, only: [:index]
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :recipes, only: [:index, :new, :show, :create, :destroy] do
    resources :recipe_foods, only: [:new, :edit, :create, :update, :destroy]
  end
  resources :shopping_lists, only: [:index]
  resources :public_recipes, only: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :manage, Recipe, user: user
    can :manage, Food, user: user
    can :read, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_food

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods

  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true

  def total_price
    recipe_foods.sum { |item| item.quantity * item.food.price }
  end

  def total_quantity
    recipe_foods.count
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe

  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable, :confirmable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :foods
  has_many :recipes

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?
  skip_before_action :verify_authenticity_token

  protected

  def after_sign_up_path_for(_resource)
    users_path
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email password current_password])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = current_user.foods
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.new(food_params)

    if @food.save
      redirect_to foods_url, notice: 'Food was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @food = Food.find(params[:id])

    if @food.destroy
      flash[:success] = 'Food was successfully deleted.'
    else
      flash[:error] = 'Error: Food could not be deleted'
    end
    redirect_to foods_url
  end

  private

  def food_params
    params.require(:food).permit(:user_id, :name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @recipes = Recipe.where(public: true).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe = current_user.recipes.find(params[:recipe_id])
    @food = current_user.foods.find(recipe_food_params[:food_id])
    @recipe_food = RecipeFood.new(recipe: @recipe, food: @food, quantity: recipe_food_params[:quantity])

    if @recipe_food.save
      flash[:success] = 'Recipe food was successfully created.'
      redirect_to recipe_url(current_user, @recipe)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
  end

  def update
    @food = current_user.foods.find(recipe_food_params[:food_id])
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(food: @food, quantity: recipe_food_params[:quantity])
      flash[:success] = 'Recipe food was successfully updated.'
      redirect_to recipe_url(current_user, @recipe_food.recipe)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = @recipe_food.recipe
    if @recipe_food.destroy
      flash[:success] = 'Recipe food was successfully removed.'
    else
      flash.now[:error] = 'Error: Recipe food could not be removed'
    end
    redirect_to recipe_url(current_user, @recipe)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = current_user.recipes
    @user_id = current_user.id
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)

    if @recipe.save
      redirect_to recipes_url, notice: 'Recipe was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes(:food, :recipe).order(:id)
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    if @recipe.destroy
      flash[:success] = 'Recipe was successfully removed.'
    else
      flash[:error] = 'Error: Recipe could not be removed'
    end
    redirect_to recipes_url
  end

  def recipe_params
    params.require(:recipe).permit(:user_id, :name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/recipes_foods_controller.rb
class RecipesFoodsController < ApplicationController
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all.order('created_at desc')
  end

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order('created_at desc')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_foods_helper.rb
module RecipesFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<div class="row">
  <a href="<%= new_food_path %>" class="btn btn-primary btn block col-sm-3 offset-sm-8">Add New</a>
</div>
<div class="row mt-5">
  <div class="col-md-4 offset-md-4">
    <table class="table">
      <thead>
        <tr>
          <th>Food</th>
          <th>Meausurement Unit</th>
          <th>Unit Price</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td><%= food.name %> </td>
            <td><%= food.measurement_unit %> </td>
            <td>$<%= food.price %> </td>
            <td>
              <% if can? :destroy, food  %>
                <%= link_to "Delete", food_path(id: food.id), class:"btn btn-outline-danger", "data-turbo-method": :delete %></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/foods/new.html.erb
<h2 class="mt-4 text-center">Add New Food</h2>
<div class="row mt-5">
  <div class="col-md-6 offset-md-3">
    <div class="card">
      <div class="card-body">
        <%= form_with model: @food, url: foods_path, class: 'flex flex-col items-center w-6/12 mx-auto' do |form| %>

          <div class="input-group input-group-outline mb-3 row">
            <label class="form-label col-sm-3">Name</label>
            <%= form.text_field :name, class: 'form-control focus:border-blue-600 col-sm-9' %>
          </div>

          <div class="input-group input-group-outline mb-3 row">
            <label class="form-label col-sm-3">Measurement Unit</label>
            <%= form.text_field :measurement_unit, class: 'form-control focus:border-blue-600 col-sm-9' %>
          </div>

          <div class="input-group input-group-outline mb-3 row">
            <label class="form-label col-sm-3">Unit Price</label>
            <%= form.number_field :price, class: 'form-control focus:border-blue-600 col-sm-9' %>
          </div>

          <div class="input-group input-group-outline mb-4 row">
            <label class="form-label col-sm-3">Quantity</label>
            <%= form.number_field :quantity, class: 'form-control focus:border-blue-600 col-sm-9' %>
          </div>
          <div class="row">
            <%= form.button "Create Food", type: "submit", class: "btn btn-primary btn-block col-md-8 offset-md-2", 'data-ripple-light': true %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recipe_foods/edit.html.erb
<h1 class="mt-4 text-center">Edit New Ingredient</h1>
<div class="row mt-5">
  <div class="col-md-6 offset-md-3">
    <div class="card">
      <div class="card-body">
        <%= form_with model: @recipe_food, url: recipe_path(recipe_id: @recipe.id), class: 'flex flex-col items-center w-6/12 mx-auto' do |form| %>
          <div class="input-group input-group-outline mb-3 row">
            <label class="form-label col-sm-3">Quantity</label>
            <%= form.number_field :quantity, class: 'form-control focus:border-blue-600 col-sm-9' %>
          </div>
          <div class="input-group input-group-outline mb-3 row">
            <label class="form-label col-sm-3">Food</label>
             <%= form.select :food_id, current_user.foods.order(name: :asc).map { |f| [f.name, f.id]}, {include_blank: true}, class: "form-control px-4 " %>
          </div>
          <div class="row">
            <%= form.button "Update Ingredient", type: "submit", class: "btn btn-success btn-block col-md-8 offset-md-2", 'data-ripple-light': true %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recipe_foods/new.html.erb
<h1 class="mt-4 text-center">Add New Ingredient</h1>
<div class="row mt-5">
  <div class="col-md-6 offset-md-3">
    <div class="card">
      <div class="card-body">
        <%= form_with model: @recipe_food, url: recipe_recipe_foods_path(@recipe), class: 'flex flex-col items-center w-6/12 mx-auto' do |form| %>
          <div class="input-group input-group-outline mb-3 row">
            <label class="form-label col-sm-3">Quantity</label>
            <%= form.number_field :quantity, class: 'form-control focus:border-blue-600 col-sm-9' %>
          </div>
          <div class="input-group input-group-outline mb-3 row">
            <label class="form-label col-sm-3">Food</label>
             <%= form.select :food_id, current_user.foods.order(name: :asc).map { |f| [f.name, f.id]}, {include_blank: true}, class: "form-control px-4 " %>
          </div>
          <div class="row">
            <%= form.button "Add Ingredient", type: "submit", class: "btn btn-primary btn-block col-md-8 offset-md-2", 'data-ripple-light': true %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="row">
<%= link_to "Create", new_recipe_path, class: "btn btn-outline-success mb-4 col-sm-3 offset-sm-9" %>
</div>
<% @recipes.each do |recipe| %>
    <div class="card mb-3">
      <div class="row p-3">
        <a href="<%= recipe_path(:id => recipe.id) %>">
          <div class="col-sm-3">
            <h2> <%= recipe.name %> </h2>
            <%= link_to "Delete", recipe_path(id: recipe.id), class: "btn btn-outline-danger", "data-turbo-method": :delete %>
          </div>
          <div class="col-sm-9">
            <p> <%= recipe.description %> </p>
          </div>
        </a>
      </div>
    </div>
<% end %>

app/views/recipes/new.html.erb
<h1 class="mt-4 text-center">Add new Recipe</h1>
<div class="row mt-5">
  <div class="col-md-6 offset-md-3">
    <div class="card">
      <div class="card-body">
        <%= form_with model: @recipe, url: recipes_path, class: 'flex flex-col items-center w-6/12 mx-auto' do |form| %>
          

          <div class="input-group input-group-outline mb-3 row">
            <label class="form-label col-sm-3">Name</label>
            <%= form.text_field :name, class: 'form-control focus:border-blue-600 col-sm-9' %>
          </div>

          <div class="input-group input-group-outline mb-3 row">
            <label class="form-label col-sm-3">Preparation time</label>
            <%= form.number_field :preparation_time, class: 'form-control focus:border-blue-600 col-sm-9' %>
          </div>

          <div class="input-group input-group-outline mb-3 row">
            <label class="form-label col-sm-3">Cooking time</label>
            <%= form.number_field :cooking_time, class: 'form-control focus:border-blue-600 col-sm-9' %>
          </div>

          <div class="input-group input-group-outline mb-4 row">
            <label class="form-label col-sm-3">Description</label>
            <%= form.text_area :description, class: 'form-control focus:border-blue-600 col-sm-9' %>
          </div>

          <div class="input-group input-group-outline mb-4 row">
            <label class="form-label col-sm-3">Public</label>
            <%= form.check_box :public, class: 'form-check-input col-sm-9' %>
          </div>
          <div class="row">
            <%= form.button "Add Recipe", type: "submit", class: "btn btn-primary btn-block col-md-8 offset-md-2", 'data-ripple-light': true %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<h2 class="text-center"><%= @recipe.name %> </h2>

<div class="d-flex justify-content-between">
  <div class="mb-3">
    <h4 class="pb-3">Preparation Time: <%= @recipe.preparation_time %> <%if @recipe.preparation_time <= 1%> hour <% else %> hours <%end%> </h4>
    <h4 class="pb-3">Cooking Time: <%= @recipe.cooking_time %> <%if @recipe.cooking_time <= 1%> hour <% else %> hours <%end%> </h4>
    <p> <%= @recipe.description%> </p>
  </div>
  <div>
    <div class="form-check form-switch">
      <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckChecked" <%if @recipe.public %> checked <%end%> disabled>
      <label class="form-check" for="flexCheckCheckedDisabled">
        Public
      </label>
    </div>
  </div>
</div>

<div class="row my-3">
  <div class="col-md-4">
    <%= link_to "Generate Shopping List", shopping_lists_path, class: "btn btn-success w-100" %>
  </div>  
  <div class="col-md-4 offset-md-4">
    <%= link_to "Add Ingredient", new_recipe_recipe_food_path(@recipe), class: "btn btn-info w-100" %>
  </div>  
</div>

<hr />

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
   <%@recipe_foods.each do |recipe_food| %>
    <tr>
      <td><%= recipe_food.food.name %></td>
      <td><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %></td>
      <td>$ <%= recipe_food.quantity * recipe_food.food.price %></td>
      <td>
        <%= link_to "Modify", edit_recipe_recipe_food_path(recipe_id: @recipe.id, id: recipe_food.id), class: "btn btn-info" %>
        <%= link_to "Remove", recipe_recipe_food_path(recipe_id: @recipe.id, id: recipe_food.id), class: "btn btn-danger", "data-turbo-method": :delete %>
      </td>
    </tr>
  </tbody>
  <%end%>
</table>