config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  root "users#index"
  resources :users, only: [:index]
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :recipes, only: [:index, :new, :show, :create, :destroy] do
    resources :recipe_foods, only: [:new, :edit, :create, :update, :destroy]
  end
  resources :shopping_lists, only: [:index]
  resources :public_recipes, only: [:index]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :manage, Recipe, user: user
    can :manage, Food, user: user
    can :read, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_food

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods

  validates :name, presence: true
  validates :preparation_time, presence: true
  validates :cooking_time, presence: true
  validates :description, presence: true

  def total_price
    recipe_foods.sum { |item| item.quantity * item.food.price }
  end

  def total_quantity
    recipe_foods.count
  end
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe

  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable, :confirmable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :foods
  has_many :recipes

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?
  skip_before_action :verify_authenticity_token

  protected

  def after_sign_up_path_for(_resource)
    users_path
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name email password current_password])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = current_user.foods
  end

  def new
    @food = Food.new
  end

  def create
    @food = current_user.foods.new(food_params)

    if @food.save
      redirect_to foods_url, notice: 'Food was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @food = Food.find(params[:id])

    if @food.destroy
      flash[:success] = 'Food was successfully deleted.'
    else
      flash[:error] = 'Error: Food could not be deleted'
    end
    redirect_to foods_url
  end

  private

  def food_params
    params.require(:food).permit(:user_id, :name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = RecipeFood.new
  end

  def create
    @recipe = current_user.recipes.find(params[:recipe_id])
    @food = current_user.foods.find(recipe_food_params[:food_id])
    @recipe_food = RecipeFood.new(recipe: @recipe, food: @food, quantity: recipe_food_params[:quantity])

    if @recipe_food.save
      flash[:success] = 'Recipe food was successfully created.'
      redirect_to recipe_url(current_user, @recipe)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
  end

  def update
    @food = current_user.foods.find(recipe_food_params[:food_id])
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(food: @food, quantity: recipe_food_params[:quantity])
      flash[:success] = 'Recipe food was successfully updated.'
      redirect_to recipe_url(current_user, @recipe_food.recipe)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = @recipe_food.recipe
    if @recipe_food.destroy
      flash[:success] = 'Recipe food was successfully removed.'
    else
      flash.now[:error] = 'Error: Recipe food could not be removed'
    end
    redirect_to recipe_url(current_user, @recipe)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:food_id, :quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = current_user.recipes
    @user_id = current_user.id
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)

    if @recipe.save
      redirect_to recipes_url, notice: 'Recipe was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes(:food, :recipe).order(:id)
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    if @recipe.destroy
      flash[:success] = 'Recipe was successfully removed.'
    else
      flash[:error] = 'Error: Recipe could not be removed'
    end
    redirect_to recipes_url
  end

  def recipe_params
    params.require(:recipe).permit(:user_id, :name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/controllers/recipes_foods_controller.rb
class RecipesFoodsController < ApplicationController
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all.order('created_at desc')
  end

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order('created_at desc')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_foods_helper.rb
module RecipesFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/recipes_foods/new.html.erb
<h1 class="mt-4 text-center">Add new a Ingredient</h1>
<div class="row mt-5">
  <div class="col-md-6 offset-md-3">
    <div class="card">
      <div class="card-body">
        <%= form_with model: @recipe_food, url: user_recipe_foods_path, class: 'flex flex-col items-center w-6/12 mx-auto' do |form| %>
          <% if @recipe_food.errors.any? %>
            <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
              <h2><%= pluralize(recipe_food.errors.count, "error") %> prevent this ingredient from being saved:</h2>

              <ul>
                <% @recipe_food.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="input-group input-group-outline mb-3 row">
            <label class="form-label col-sm-3">Name</label>
            <%= form.text_field :name, class: 'form-control focus:border-blue-600 col-sm-9' %>
          </div>

          <div class="input-group input-group-outline mb-3 row">
            <label class="form-label col-sm-3">Quantity time</label>
            <%= form.number_field :quantity, class: 'form-control focus:border-blue-600 col-sm-9' %>
          </div>

          <div class="input-group input-group-outline mb-3 row">
            <label class="form-label col-sm-3">Food ID</label>
            <%= form.number_field :food_id, class: 'form-control focus:border-blue-600 col-sm-9' %>
          </div>

          <div class="input-group input-group-outline mb-4 row">
            <label class="form-label col-sm-3">Recipe ID</label>
            <%= form.number_field :recipe_id, class: 'form-control focus:border-blue-600 col-sm-9' %>
          </div>
          <div class="row">
            <%= form.button "Add Ingredient", type: "submit", class: "btn btn-primary btn-block col-md-8 offset-md-2", 'data-ripple-light': true %>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>